In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('train.csv')

In [3]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [5]:
data=data[["Id","MSZoning","Utilities","Neighborhood","Condition1","BldgType","HouseStyle","OverallQual","YearBuilt","Foundation","GrLivArea","TotRmsAbvGrd","GarageType","GarageArea","FullBath","HalfBath","BedroomAbvGr"]]

In [6]:
data.head()

,Id,MSZoning,Utilities,Neighborhood,Condition1,BldgType,HouseStyle,OverallQual,YearBuilt,Foundation,GrLivArea,TotRmsAbvGrd,GarageType,GarageArea,FullBath,HalfBath,BedroomAbvGr
0,1,RL,AllPub,CollgCr,Norm,1Fam,2Story,7,2003,PConc,1710,8,Attchd,548,2,1,3
1,2,RL,AllPub,Veenker,Feedr,1Fam,1Story,6,1976,CBlock,1262,6,Attchd,460,2,0,3
2,3,RL,AllPub,CollgCr,Norm,1Fam,2Story,7,2001,PConc,1786,6,Attchd,608,2,1,3
3,4,RL,AllPub,Crawfor,Norm,1Fam,2Story,7,1915,BrkTil,1717,7,Detchd,642,1,0,3
4,5,RL,AllPub,NoRidge,Norm,1Fam,2Story,8,2000,PConc,2198,9,Attchd,836,2,1,4

In [7]:
data.columns

Index(['Id', 'MSZoning', 'Utilities', 'Neighborhood', 'Condition1', 'BldgType',
       'HouseStyle', 'OverallQual', 'YearBuilt', 'Foundation', 'GrLivArea',
       'TotRmsAbvGrd', 'GarageType', 'GarageArea', 'FullBath', 'HalfBath',
       'BedroomAbvGr'],
      dtype='object')

In [8]:
data.dtypes

Id               int64
MSZoning        object
Utilities       object
Neighborhood    object
Condition1      object
BldgType        object
HouseStyle      object
OverallQual      int64
YearBuilt        int64
Foundation      object
GrLivArea        int64
TotRmsAbvGrd     int64
GarageType      object
GarageArea       int64
FullBath         int64
HalfBath         int64
BedroomAbvGr     int64
dtype: object

In [9]:
data=data.drop("Id",axis=1)

In [10]:
data.head()

,MSZoning,Utilities,Neighborhood,Condition1,BldgType,HouseStyle,OverallQual,YearBuilt,Foundation,GrLivArea,TotRmsAbvGrd,GarageType,GarageArea,FullBath,HalfBath,BedroomAbvGr
0,RL,AllPub,CollgCr,Norm,1Fam,2Story,7,2003,PConc,1710,8,Attchd,548,2,1,3
1,RL,AllPub,Veenker,Feedr,1Fam,1Story,6,1976,CBlock,1262,6,Attchd,460,2,0,3
2,RL,AllPub,CollgCr,Norm,1Fam,2Story,7,2001,PConc,1786,6,Attchd,608,2,1,3
3,RL,AllPub,Crawfor,Norm,1Fam,2Story,7,1915,BrkTil,1717,7,Detchd,642,1,0,3
4,RL,AllPub,NoRidge,Norm,1Fam,2Story,8,2000,PConc,2198,9,Attchd,836,2,1,4

In [11]:
data.dtypes

MSZoning        object
Utilities       object
Neighborhood    object
Condition1      object
BldgType        object
HouseStyle      object
OverallQual      int64
YearBuilt        int64
Foundation      object
GrLivArea        int64
TotRmsAbvGrd     int64
GarageType      object
GarageArea       int64
FullBath         int64
HalfBath         int64
BedroomAbvGr     int64
dtype: object

In [12]:
data["MSZoning"].value_counts()

RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

In [13]:
data["Utilities"].value_counts()

AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

In [14]:
columns=data.columns

In [15]:
print(columns)
print(type(columns))

Index(['MSZoning', 'Utilities', 'Neighborhood', 'Condition1', 'BldgType',
       'HouseStyle', 'OverallQual', 'YearBuilt', 'Foundation', 'GrLivArea',
       'TotRmsAbvGrd', 'GarageType', 'GarageArea', 'FullBath', 'HalfBath',
       'BedroomAbvGr'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [16]:
for i in columns:
    print("*******")
    print(i)
    col_name=i
    print(data[col_name].value_counts())

*******
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64
*******
Utilities
AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64
*******
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64
*******
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64
*******
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64
*******
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64
*******
OverallQual
5     397
6     374
7     319
8     168
4     116
9      43
3      20
10     18
2       3
1       2
Name: OverallQual, dtype: int64
*******
YearBuilt
2006    67
2005    64
2004    54
2007    49
2003    45
        ..
1875     1
1911     1
1917     1
1872     1
1905     1
Name: YearBuilt, Length: 112, dtype: int64
*******
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64
*******
GrLivArea
864     22
1040    14
894     11
1456    10
848     10
        ..
2296     1
1123     1
1199     1
1473     1
1256     1
Name: GrLivArea, Length: 861, dtype: int64
*******
TotRmsAbvGrd
6     402
7     329
5     275
8     187
4      97
9      75
10     47
11     18
3      17
12     11
2       1
14      1
Name: TotRmsAbvGrd, dtype: int64
*******
GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64
*******
GarageArea
0      81
440    49
576    47
240    38
484    34
       ..
320     1
594     1
831     1
878     1
192     1
Name: GarageArea, Length: 441, dtype: int64
*******
FullBath
2    768
1    650
3     33
0      9
Name: FullBath, dtype: int64
*******
HalfBath
0    913
1    535
2     12
Name: HalfBath, dtype: int64
*******
BedroomAbvGr
3    804
2    358
4    213
1     50
5     21
6      7
0      6
8      1
Name: BedroomAbvGr, dtype: int64

In [17]:
data["Age"]=2022-data["YearBuilt"]

In [18]:
data["Age"].value_counts()

16     67
17     64
18     54
15     49
19     45
       ..
147     1
111     1
105     1
150     1
117     1
Name: Age, Length: 112, dtype: int64

In [19]:
data=data.drop("YearBuilt",axis=1)

In [20]:
data.head()

,MSZoning,Utilities,Neighborhood,Condition1,BldgType,HouseStyle,OverallQual,Foundation,GrLivArea,TotRmsAbvGrd,GarageType,GarageArea,FullBath,HalfBath,BedroomAbvGr,Age
0,RL,AllPub,CollgCr,Norm,1Fam,2Story,7,PConc,1710,8,Attchd,548,2,1,3,19
1,RL,AllPub,Veenker,Feedr,1Fam,1Story,6,CBlock,1262,6,Attchd,460,2,0,3,46
2,RL,AllPub,CollgCr,Norm,1Fam,2Story,7,PConc,1786,6,Attchd,608,2,1,3,21
3,RL,AllPub,Crawfor,Norm,1Fam,2Story,7,BrkTil,1717,7,Detchd,642,1,0,3,107
4,RL,AllPub,NoRidge,Norm,1Fam,2Story,8,PConc,2198,9,Attchd,836,2,1,4,22

In [21]:
data.dtypes

MSZoning        object
Utilities       object
Neighborhood    object
Condition1      object
BldgType        object
HouseStyle      object
OverallQual      int64
Foundation      object
GrLivArea        int64
TotRmsAbvGrd     int64
GarageType      object
GarageArea       int64
FullBath         int64
HalfBath         int64
BedroomAbvGr     int64
Age              int64
dtype: object

In [22]:
data.shape

(1460, 16)

In [23]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [24]:
X_train=data
Y_train=pd.read_csv("train.csv")["SalePrice"]

In [25]:
X_train.shape

(1460, 16)

In [26]:
Y_train.shape

(1460,)

In [27]:
data_test=pd.read_csv("test.csv")
data_test=data_test[["Id","MSZoning","Utilities","Neighborhood","Condition1","BldgType","HouseStyle","OverallQual","YearBuilt","Foundation","GrLivArea","TotRmsAbvGrd","GarageType","GarageArea","FullBath","HalfBath","BedroomAbvGr"]]
data_test["Age"]=2022-data_test["YearBuilt"]
data_test.drop("YearBuilt",axis=1)

,Id,MSZoning,Utilities,Neighborhood,Condition1,BldgType,HouseStyle,OverallQual,Foundation,GrLivArea,TotRmsAbvGrd,GarageType,GarageArea,FullBath,HalfBath,BedroomAbvGr,Age
0,1461,RH,AllPub,NAmes,Feedr,1Fam,1Story,5,CBlock,896,5,Attchd,730.0,1,0,2,61
1,1462,RL,AllPub,NAmes,Norm,1Fam,1Story,6,CBlock,1329,6,Attchd,312.0,1,1,3,64
2,1463,RL,AllPub,Gilbert,Norm,1Fam,2Story,5,PConc,1629,6,Attchd,482.0,2,1,3,25
3,1464,RL,AllPub,Gilbert,Norm,1Fam,2Story,6,PConc,1604,7,Attchd,470.0,2,1,3,24
4,1465,RL,AllPub,StoneBr,Norm,TwnhsE,1Story,8,PConc,1280,5,Attchd,506.0,2,0,2,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,RM,AllPub,MeadowV,Norm,Twnhs,2Story,4,CBlock,1092,5,NaN,0.0,1,1,3,52
1455,2916,RM,AllPub,MeadowV,Norm,TwnhsE,2Story,4,CBlock,1092,6,CarPort,286.0,1,1,3,52
1456,2917,RL,AllPub,Mitchel,Norm,1Fam,1Story,5,CBlock,1224,7,Detchd,576.0,1,0,4,62
1457,2918,RL,AllPub,Mitchel,Norm,1Fam,SFoyer,5,PConc,970,6,NaN,0.0,1,0,3,30
1458,2919,RL,AllPub,Mitchel,Norm,1Fam,2Story,7,PConc,2000,9,Attchd,650.0,2,1,3,29

In [28]:
column_trans=make_column_transformer((OneHotEncoder(sparse=False),["MSZoning","Utilities","Neighborhood","Condition1","BldgType","HouseStyle","Foundation","GarageType"]),remainder='passthrough')

In [29]:
scaler=StandardScaler()

In [30]:
lr=LinearRegression(normalize=True)

In [31]:
pipe=make_pipeline(column_trans,scaler,lr)

In [32]:
pipe.fit(X_train,Y_train)

c:\users\91955\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['MSZoning', 'Utilities',
                                                   'Neighborhood', 'Condition1',
                                                   'BldgType', 'HouseStyle',
                                                   'Foundation',
                                                   'GarageType'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression(normalize=True))])

In [34]:
X_test=pd.read_csv("test.csv")
X_test=X_test[["Id","MSZoning","Utilities","Neighborhood","Condition1","BldgType","HouseStyle","OverallQual","YearBuilt","Foundation","GrLivArea","TotRmsAbvGrd","GarageType","GarageArea","FullBath","HalfBath","BedroomAbvGr"]]

X_test=X_test.drop("Id",axis=1)
#y_pred_lr=pipe.predict(X_test)

In [35]:
X_test["Age"]=2022-X_test["YearBuilt"]

In [36]:
X_test=X_test.drop("YearBuilt",axis=1)

In [37]:
X_test.head()

,MSZoning,Utilities,Neighborhood,Condition1,BldgType,HouseStyle,OverallQual,Foundation,GrLivArea,TotRmsAbvGrd,GarageType,GarageArea,FullBath,HalfBath,BedroomAbvGr,Age
0,RH,AllPub,NAmes,Feedr,1Fam,1Story,5,CBlock,896,5,Attchd,730.0,1,0,2,61
1,RL,AllPub,NAmes,Norm,1Fam,1Story,6,CBlock,1329,6,Attchd,312.0,1,1,3,64
2,RL,AllPub,Gilbert,Norm,1Fam,2Story,5,PConc,1629,6,Attchd,482.0,2,1,3,25
3,RL,AllPub,Gilbert,Norm,1Fam,2Story,6,PConc,1604,7,Attchd,470.0,2,1,3,24
4,RL,AllPub,StoneBr,Norm,TwnhsE,1Story,8,PConc,1280,5,Attchd,506.0,2,0,2,30

In [38]:
X_test.shape

(1459, 16)

In [40]:
Null_check=X_test.isnull()

In [41]:
Null_check

,MSZoning,Utilities,Neighborhood,Condition1,BldgType,HouseStyle,OverallQual,Foundation,GrLivArea,TotRmsAbvGrd,GarageType,GarageArea,FullBath,HalfBath,BedroomAbvGr,Age
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1455,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1456,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1457,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1458,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [42]:
X_test=X_test.dropna()

In [43]:
X_test.shape

(1377, 16)

In [44]:
y_pred_lr=pipe.predict(X_test)

In [45]:
y_pred_lr

array([111444.41407465, 163399.40393966, 163632.10081181, ...,
        66793.4026843 , 141176.34186129, 231476.58333888])

In [83]:
import pickle

In [84]:
pickle.dump(pipe,open('LinearModel.pkl','wb'))